### ISSUE TITLE
meta-learning doesn't work for the ssl model I trained（it works， sorry）

### ISSUE THREAD

**Issue by IceLeeCool** [phecy/SSL-FEW-SHOT#10]

**Comment by RezwanCode** [comment]
Hi, I am unable to run the whole program in google colab, can you guide me a bit on how to run this whole program. I am new to ML

**Comment by IceLeeCool** [comment]
Sorry, my programming ability is not very well, all i did is using the parameters provided in github and run the code, and it works. I think it will run if you run the code in github. Good luck.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "phecy/SSL-FEW-SHOT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月22日(星期天) 下午2:09
收件人:&nbsp;"phecy/SSL-FEW-SHOT"<SSL-FEW-SHOT@noreply.github.com&gt;;
抄送:&nbsp;"李冰斌"<1370919440@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [phecy/SSL-FEW-SHOT] meta-learning doesn't work for the ssl model I trained（it works， sorry） (#10)





 
Hi, I am unable to run the whole program in google colab, can you guide me a bit on how to run this whole program. I am new to ML
