### ISSUE TITLE
Get KeyError: 'params' when loading model state dict

### ISSUE THREAD

**Issue by GabirYousef** [phecy/SSL-FEW-SHOT#12]
I want to run eval_protonet.py script, but I can't load the model weights. I keep the default paramerters and pass the model weights like this:

`python eval_protonet.py --model_path /content/SSL-FEW-SHOT/saves/initialization/miniimagenet/mini_imagenet_ndf192_rkhs1536_rd8_ssl_cpt.pth `

I got this error: 

/content/SSL-FEW-SHOT
{'dataset': 'MiniImageNet',
 'gpu': '0',
 'model_path': '/content/SSL-FEW-SHOT/saves/initialization/miniimagenet/imagenet900_ndf192_rkhs_1536_rd8_sl_cpt.pth',
 'model_type': 'ConvNet',
 'nd': 10,
 'ndf': 256,
 'query': 15,
 'rkhs': 2048,
 'shot': 1,
 'temperature': 1,
 'way': 5}
using gpu: 0
Traceback (most recent call last):
  File "eval_protonet.py", line 53, in <module>
    model.load_state_dict(torch.load(args.model_path)['params'])
KeyError: 'params'

any help?

**Comment by Lyrics1988** [comment]
Hi GabirYousef,

Thanks for your attention to our work. 

Please run the  'train_protonet.py' as guided in ReadMe file, and please double-check your PyTorch version.

Cheers

**Comment by GabirYousef** [comment]
I got it to work. thanks a lot

**Comment by eladmeir** [comment]
Hey @GabirYousef 
Can you please share your fix? I have encountered the same problem and couldn't make it work...
Thanks
