### ISSUE TITLE
How to get Image900 dataset?

### ISSUE THREAD

**Issue by semi-supervised-paper** [phecy/SSL-FEW-SHOT#4]
Hi,

I notice that you have done experiments on ImageNet with 900 classes (without 100 classes in Mini-ImageNet). I wonder how you get this dataset. Could you provide the related codes?

Thanks.

**Comment by phecy** [comment]
ImageNet900 is all images from ImageNet1K except MiniImageNet. For more detail
https://gist.github.com/phecy/9129d256c82240287717a81e8723c606
